name: Deploy mkdocs

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools
            pip install -r docs/requirements.txt
            pip install -e .[all]
            pip install omegaconf effdet@https://github.com/rwightman/efficientdet-pytorch/archive/master.zip#egg=effdet-0.1.4
      - name: Deploy the docs
        run:  |
          cd docs
          python autogen.py
          mkdocs build
          mkdocs gh-deploy --force 